### ISSUE TITLE
هل فيه خطة عمل؟

### ISSUE THREAD

**Issue by Alaboudi1** [abo3desa/quran-project-repo#1]
<div dir="rtl">
هل فيه متطلبات تمشي معها؟ ولا توك ماسويتها؟؟

</div>

**Comment by abo3desa** [comment]
الي افكر فيه. بعد ما يدخل اليوزر المده و يحدد الوقت و الايام الي يقرا فيها يكون عنده داشبورد مقسمه توريه الي قراه 
 في اسبوع, شهر على حسب المده الي دخلها و يكون عنده جدول اليوم يوريه وش المفروض يقرا اليوم ويقدر مثلا اذا كان مايقدر يقرا في وقت معين يقدر يعين وقت ثاني
