### ISSUE TITLE
تقسيم القرآن على الخطه

### ISSUE THREAD

**Issue by abo3desa** [abo3desa/quran-project-repo#7]

**Comment by Alaboudi1** [comment]
https://jsbin.com/taqiner/1/edit?js,console
<div dir="rtl">
هذه الخوازمية. أتوقع يبيلها بعض التعديلات. أبيك تختبرها وتشوف وتقترح أي تعديل لو تبي

</div>

**Comment by Alaboudi1** [comment]
أكتشفت شي! أن ترتيب القراءة بعدد الأيات ممكن يخليك تقرا في بعض الأيام اكثر من غيرها. يعني مثلا في سورة البقرة في وجه كامل أيه وحده. وصورة مثل الرحمان أياتها قصيرة  فتقرا أقل.

**Comment by abo3desa** [comment]
زياده القراءة في السور القصيرة ممكن يكون حل

**Comment by Alaboudi1** [comment]
ممكن🤔

**Comment by Alaboudi1** [comment]
<div dir="rtl">
الخوازمية الآن أسرع ب 70 % من النسخة الأولى
</div>
https://jsbin.com/hapenux/2/edit?js,console

أبيك تختبر إذا ما تغير شي في النتائج...

**Comment by Alaboudi1** [comment]
<div dir="rtl">
70% كثير. خلنا نقول 30%
هههه

</div>

**Comment by abo3desa** [comment]
ممتازه بس الظاهر ان الكود اذا شغلته يسوي تعديل على المصفوفه الاصلية لو تجرب تطبع للكونسل مرتين المره الثانيه ما راح تشتغل

**Comment by Alaboudi1** [comment]
<div dir="rtl">
أيه.
المفترض ننسخ المصفوفة  بإستخدام
</div>
new_array = old_array.msp( obj => Object.assign({}, obj));

**Comment by abo3desa** [comment]
الكود فيه مشكلة لما احط خطه طويله مثل
``getplan(20, 7, 5, suras.reverse())``
اللينجث حق الخطه المفروض يصير ناتج ضرب 20 و 7 و 5 بس يطلع لي ناقص  شيك هنا
https://jsbin.com/fabahacowu/edit?js,console

**Comment by Alaboudi1** [comment]
أتوقع أنه بسبب 
Math.ceil
فبدال ما يقرأ الشخص 5.1 أيات، صار يقرأ 6

**Comment by Alaboudi1** [comment]
جرب تمسح 
Math.ceil
وبيضبط معك العدد بس الأيات بتطلع بكسور
👎
